version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - "discovery.type=single-node"
      - "DISABLE_SECURITY_PLUGIN=true"  # Disable HTTPS for OpenSearch
    ports:
      - "9200:9200"
    networks:
      - my_network
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - my_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my_network
#  spring-app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - elasticsearch
#    networks:
#      - my_network

  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8082:8080"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
